name: pierPy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - scipy
  - ipython
  - matplotlib
  - pip
  - pytorch
  - torchvision
  - requests
  - time
  - cudatoolkit